Traceback (most recent call last):
  File "/home/phuijse/.conda/envs/info183/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/phuijse/.conda/envs/info183/lib/python3.8/site-packages/nbclient/client.py", line 1082, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/phuijse/.conda/envs/info183/lib/python3.8/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/phuijse/.conda/envs/info183/lib/python3.8/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/home/phuijse/.conda/envs/info183/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/phuijse/.conda/envs/info183/lib/python3.8/site-packages/nbclient/client.py", line 535, in async_execute
    await self.async_execute_cell(
  File "/home/phuijse/.conda/envs/info183/lib/python3.8/site-packages/nbclient/client.py", line 827, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/home/phuijse/.conda/envs/info183/lib/python3.8/site-packages/nbclient/client.py", line 735, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from numpy.lib.stride_tricks import as_strided
fig, ax = plt.subplots(3, figsize=(9, 5))
t, dt = np.linspace(0, 5, num=500, retstep=True)
u = np.sin(2.0*np.pi*t*5)
#u[250:] += 5  # Cambio abrupto en la media
#u += 2*t  #  Tendencia lineal
#u += u*(0.5 + 0.5*np.cos(2.0*np.pi*t/2))  # Tremolo (AM)
def update(mu, L, rseed):
    np.random.seed(rseed)
    u_noise = u + 0.5*np.random.randn(len(t)) 
    w = np.zeros(shape=(L+1, ))
    ax[0].cla(); ax[1].cla(); ax[2].cla(); 
    #LMS
    u_pred = np.zeros(shape=(len(u), ))
    for k in range(L+1, len(u)-1):
        norm = np.sum(u_noise[k-L-1:k]**2) + 1e-6
        u_pred[k] = np.dot(w, u_noise[k-L-1:k])
        w += 2*mu*(u_noise[k] - u_pred[k])*u_noise[k-L-1:k]/norm
    u_pred[k+1] = np.dot(w, u_noise[k-L-1:k])
    ax[0].plot(t, u_noise, 'k.', alpha=0.5); 
    ax[0].plot(t, u, 'g-', alpha=0.5);  ax[0].plot(t, u_pred); 
    
    ax[1].plot((u - u_pred)**2, label='LMS')
    k, Hk = scipy.signal.freqz(b=w, a=1)
    ax[2].plot(k/(2*dt*np.pi), np.abs(Hk))
    
interact(update, mu=SelectionSlider_nice(options=[1e-4, 1e-3, 0.01, 0.1, 0.2, 1.]),
         L=SelectionSlider_nice(options=[1, 5, 10, 20, 50], value=10), rseed=IntSlider_nice());
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
[0;32m<ipython-input-3-af4dd41b9575>[0m in [0;36m<module>[0;34m[0m
[1;32m     25[0m     [0max[0m[0;34m[[0m[0;36m2[0m[0;34m][0m[0;34m.[0m[0mplot[0m[0;34m([0m[0mk[0m[0;34m/[0m[0;34m([0m[0;36m2[0m[0;34m*[0m[0mdt[0m[0;34m*[0m[0mnp[0m[0;34m.[0m[0mpi[0m[0;34m)[0m[0;34m,[0m [0mnp[0m[0;34m.[0m[0mabs[0m[0;34m([0m[0mHk[0m[0;34m)[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m     26[0m [0;34m[0m[0m
[0;32m---> 27[0;31m interact(update, mu=SelectionSlider_nice(options=[1e-4, 1e-3, 0.01, 0.1, 0.2, 1.]),
[0m[1;32m     28[0m          L=SelectionSlider_nice(options=[1, 5, 10, 20, 50], value=10), rseed=IntSlider_nice());

[0;31mNameError[0m: name 'interact' is not defined
NameError: name 'interact' is not defined

