Traceback (most recent call last):
  File "/home/phuijse/.conda/envs/info183/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/phuijse/.conda/envs/info183/lib/python3.8/site-packages/nbclient/client.py", line 1082, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/phuijse/.conda/envs/info183/lib/python3.8/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/phuijse/.conda/envs/info183/lib/python3.8/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/home/phuijse/.conda/envs/info183/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/phuijse/.conda/envs/info183/lib/python3.8/site-packages/nbclient/client.py", line 535, in async_execute
    await self.async_execute_cell(
  File "/home/phuijse/.conda/envs/info183/lib/python3.8/site-packages/nbclient/client.py", line 827, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/home/phuijse/.conda/envs/info183/lib/python3.8/site-packages/nbclient/client.py", line 735, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
fig, ax = plt.subplots()
ax.plot(r, alpha=0.5)
ax.plot(rh, alpha=.5)
ax.plot(s, alpha=.5)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
[0;32m<ipython-input-4-82884f36aa86>[0m in [0;36m<module>[0;34m[0m
[1;32m      2[0m [0max[0m[0;34m.[0m[0mplot[0m[0;34m([0m[0mr[0m[0;34m,[0m [0malpha[0m[0;34m=[0m[0;36m0.5[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      3[0m [0max[0m[0;34m.[0m[0mplot[0m[0;34m([0m[0mrh[0m[0;34m,[0m [0malpha[0m[0;34m=[0m[0;36m.5[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 4[0;31m [0max[0m[0;34m.[0m[0mplot[0m[0;34m([0m[0ms[0m[0;34m,[0m [0malpha[0m[0;34m=[0m[0;36m.5[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;31mNameError[0m: name 's' is not defined
NameError: name 's' is not defined

